name: Angular CI

defaults:
  run:
    working-directory: ./frontend

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Clean Install
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
